/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/me/info": {
    get: operations["read_teacher_me_info_get"];
  };
  "/signup": {
    post: operations["register_teacher_signup_post"];
  };
  "/me/password": {
    patch: operations["change_teacher_password_me_password_patch"];
  };
  "/login/token": {
    post: operations["login_for_access_token_login_token_post"];
  };
  "/login": {
    post: operations["login_login_post"];
  };
  "/join/room/{room_id}": {
    post: operations["student_join_room_join_room__room_id__post"];
  };
}

export interface components {
  schemas: {
    /** Body_login_for_access_token_login_token_post */
    Body_login_for_access_token_login_token_post: {
      /** Grant Type */
      grant_type?: Partial<string> & Partial<unknown>;
      /** Username */
      username: string;
      /** Password */
      password: string;
      /**
       * Scope
       * @default
       */
      scope?: string;
      /** Client Id */
      client_id?: Partial<string> & Partial<unknown>;
      /** Client Secret */
      client_secret?: Partial<string> & Partial<unknown>;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** StudentPublic */
    StudentPublic: {
      /** Room Id */
      room_id: string;
      /** Name */
      name: string;
      /** Id */
      id: number;
    };
    /** StudentRegister */
    StudentRegister: {
      /** Room Id */
      room_id: string;
      /** Name */
      name: string;
    };
    /** TeacherCreate */
    TeacherCreate: {
      /** Email */
      email: string;
      /** Name */
      name: string;
      /** Google Id */
      google_id?: Partial<string> & Partial<unknown>;
      /** Password */
      password: string;
    };
    /** TeacherLogin */
    TeacherLogin: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** TeacherPassword */
    TeacherPassword: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** TeacherPublic */
    TeacherPublic: {
      /** Email */
      email: string;
      /** Name */
      name: string;
      /** Google Id */
      google_id?: Partial<string> & Partial<unknown>;
      /** Id */
      id: number;
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (Partial<string> & Partial<number>)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
}

export interface operations {
  read_teacher_me_info_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TeacherPublic"];
        };
      };
    };
  };
  register_teacher_signup_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TeacherPublic"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeacherCreate"];
      };
    };
  };
  change_teacher_password_me_password_patch: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeacherPassword"];
      };
    };
  };
  login_for_access_token_login_token_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_login_token_post"];
      };
    };
  };
  login_login_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeacherLogin"];
      };
    };
  };
  student_join_room_join_room__room_id__post: {
    parameters: {
      path: {
        room_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StudentPublic"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StudentRegister"];
      };
    };
  };
}

export interface external {}
