/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  StudentPublic
} from '.././model'

export const getStudentJoinRoomJoinRoomRoomIdPostResponseMock = (overrideResponse: any = {}): StudentPublic => ({id: faker.number.int({min: undefined, max: undefined}), name: faker.word.sample(), room_id: faker.word.sample(), ...overrideResponse})


export const getStudentJoinRoomJoinRoomRoomIdPostMockHandler = (overrideResponse?: StudentPublic) => {
  return http.post('*/join/room/:roomId', async () => {
    await delay(1000);
    return new HttpResponse(JSON.stringify(overrideResponse ? overrideResponse : getStudentJoinRoomJoinRoomRoomIdPostResponseMock()),
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getRoomMock = () => [
  getStudentJoinRoomJoinRoomRoomIdPostMockHandler()
]
