/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginForAccessTokenLoginTokenPostClientId } from './bodyLoginForAccessTokenLoginTokenPostClientId';
import type { BodyLoginForAccessTokenLoginTokenPostClientSecret } from './bodyLoginForAccessTokenLoginTokenPostClientSecret';
import type { BodyLoginForAccessTokenLoginTokenPostGrantType } from './bodyLoginForAccessTokenLoginTokenPostGrantType';

export interface BodyLoginForAccessTokenLoginTokenPost {
  client_id: BodyLoginForAccessTokenLoginTokenPostClientId;
  client_secret: BodyLoginForAccessTokenLoginTokenPostClientSecret;
  grant_type: BodyLoginForAccessTokenLoginTokenPostGrantType;
  password: string;
  scope?: string;
  username: string;
}
