/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { EndRoomBodyQuestions } from './endRoomBodyQuestions';
import type { EndRoomBodyStudents } from './endRoomBodyStudents';

export interface EndRoomBody {
  activeQuestionIndex: number;
  questionOrder: number[];
  questions: EndRoomBodyQuestions;
  status: string;
  students: EndRoomBodyStudents;
}
