/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { StudentEndModel } from './studentEndModel';

export type EndRoomBodyStudents = {[key: string]: StudentEndModel};
