/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Answer } from './answer';
import type { LoaderQuestionDataTimeLimit } from './loaderQuestionDataTimeLimit';
import type { LoaderQuestionDataTimeStart } from './loaderQuestionDataTimeStart';
import type { LoaderQuestionDataType } from './loaderQuestionDataType';

export interface LoaderQuestionData {
  answers: Answer[];
  created_at: string;
  explaination: string;
  id: number;
  tilte: string;
  time_limit: LoaderQuestionDataTimeLimit;
  time_start?: LoaderQuestionDataTimeStart;
  type: LoaderQuestionDataType;
  updated_at: string;
}
