/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { Answer } from './answer';
import type { QuestionAnswerTimeLimit } from './questionAnswerTimeLimit';
import type { QuestionAnswerType } from './questionAnswerType';

export interface QuestionAnswer {
  answers: Answer[];
  created_at: string;
  explaination: string;
  id: number;
  tilte: string;
  time_limit: QuestionAnswerTimeLimit;
  type: QuestionAnswerType;
  updated_at: string;
}
