/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionPublicTimeLimit } from './questionPublicTimeLimit';
import type { QuestionPublicType } from './questionPublicType';

export interface QuestionPublic {
  created_at: string;
  explaination: string;
  id: number;
  tilte: string;
  time_limit: QuestionPublicTimeLimit;
  type: QuestionPublicType;
  updated_at: string;
}
