/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface QuestionResponseCreate {
  answer_id: number;
  question_id: number;
  room_id: number;
  student_id: number;
}
