/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AnswerCreate } from './answerCreate';
import type { QuestionAnswerCreateTimeLimit } from './questionAnswerCreateTimeLimit';
import type { QuestionAnswerCreateType } from './questionAnswerCreateType';

export interface QuestionAnswerCreate {
  answers: AnswerCreate[];
  explaination: string;
  tilte: string;
  time_limit: QuestionAnswerCreateTimeLimit;
  type: QuestionAnswerCreateType;
}
