/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionAnswer } from './questionAnswer';

export interface QuizQuestions {
  created_at: string;
  description: string;
  id: number;
  questions: QuestionAnswer[];
  teacher_id: number;
  tilte: string;
  updated_at: string;
}
