/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { QuizCreatedAt } from './quizCreatedAt';
import type { QuizId } from './quizId';
import type { QuizTeacherId } from './quizTeacherId';
import type { QuizUpdatedAt } from './quizUpdatedAt';

export interface Quiz {
  created_at?: QuizCreatedAt;
  description: string;
  id?: QuizId;
  teacher_id?: QuizTeacherId;
  tilte: string;
  updated_at?: QuizUpdatedAt;
}
