/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoomPublicEndedAt } from './roomPublicEndedAt';

export interface RoomPublic {
  created_at: string;
  ended_at: RoomPublicEndedAt;
  id: number;
  is_published?: boolean;
  is_randomized: boolean;
  name: string;
  quiz_id: number;
  updated_at: string;
}
