/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RoomWithQuizEndedAt } from './roomWithQuizEndedAt';
import type { QuizQuestions } from './quizQuestions';

export interface RoomWithQuiz {
  created_at: string;
  ended_at: RoomWithQuizEndedAt;
  id: number;
  is_published?: boolean;
  is_randomized: boolean;
  name: string;
  quiz: QuizQuestions;
  quiz_id: number;
  updated_at: string;
}
