/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface RoomCreate {
  is_published?: boolean;
  is_randomized: boolean;
  name: string;
  quiz_id: number;
}
