/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TeacherCreateGoogleId } from './teacherCreateGoogleId';

export interface TeacherCreate {
  email: string;
  google_id?: TeacherCreateGoogleId;
  name: string;
  password: string;
}
