/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TeacherPublicGoogleId } from './teacherPublicGoogleId';

export interface TeacherPublic {
  email: string;
  google_id?: TeacherPublicGoogleId;
  id: number;
  name: string;
}
