/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw'


export const getStartupEvent2StartupGetMockHandler = () => {
  return http.get('*/startup', async () => {
    await delay(1000);
    return new HttpResponse(null,
      {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
        }
      }
    )
  })
}
export const getDefaultMock = () => [
  getStartupEvent2StartupGetMockHandler()
]
